config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  root "articles#index"

  resources :articles do
    resources :comments
  end

  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container mx-auto p-8">
  <%= form_with model: article, class: "max-w-lg mx-auto" do |form| %>
    <div class="mb-4">
      <%= form.label :title, class: "block text-gray-700 font-bold mb-2" %>
      <%= form.text_field :title, class: "form-input mt-1 block w-full" %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div class="text-red-500 mt-1"><%= message %></div>
      <% end %>
    </div>
    <div class="mb-4">
      <%= form.label :body, class: "block text-gray-700 font-bold mb-2" %>
      <%= form.text_area :body, class: "form-textarea mt-1 block w-full" %>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div class="text-red-500 mt-1"><%= message %></div>
      <% end %>
    </div>
    <div class="mb-4">
      <%= form.label :status, class: "block text-gray-700 font-bold mb-2" %>
      <%= form.select :status, Visible::VALID_STATUSES, { selected: article.status || 'public' }, class: "form-select mt-1 block w-full" %>
    </div>
    <div>
      <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
</div>

app/views/articles/edi.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="container mx-auto p-8">
  <h1 class="text-3xl font-bold mb-4">Articles</h1>
  <p class="mb-4">Our blog has <span class="font-bold"><%= Article.public_count %></span> articles and counting!</p>
  <ul class="space-y-4 mb-8">
    <% @articles.each do |article| %>
      <% unless article.archived? %>
        <li class="link">
          <%= link_to article.title, article %>
        </li>
      <% end %>
    <% end %>
  </ul>
  <%= link_to "New Article", new_article_path, class: 'link' %>
</div>

app/views/articles/new.html.erb
<div class='flex flex-col mx-auto'>

<h1 class='text-center'>New Article</h1>

<%= render "form", article: @article %>

<%= link_to "Back", articles_path, class: "link" %>

</div>

app/views/articles/show.html.erb
<div class="container mx-auto p-8">
  <h1 class="text-3xl font-bold mb-4"><%= @article.title %></h1>

  <p class="mb-4"><%= @article.body %></p>

  <ul class="flex space-x-4 mb-4">
    <li>
      <%= link_to "Edit", edit_article_path(@article), class: "text-blue-500 hover:underline" %>
    </li>
    <li>
      <%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: "text-red-500 hover:underline" %>
    </li>
  </ul>

  <h2 class="text-2xl font-bold mb-2">Comments</h2>
  <%= render @article.comments %>

  <h2 class="text-2xl font-bold mb-2">Add a comment:</h2>
  <%= render 'comments/form' %>

  <%= link_to "Back", articles_path, class: "text-blue-500 hover:underline" %>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Str</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <main class="container mx-auto mt-28 px-5 flex min-h-[50vh]">
      <%= yield %>
    </main>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="mx-auto mt-40 max-w-7xl overflow-hidden px-6 pb-20 sm:mt-64 sm:pb-24 lg:px-8">
  <nav class="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">
    <div class="pb-6">
      <a href="/" class="text-sm leading-6 text-gray-600 hover:text-gray-900">Blog</a>
    </div>
    <div class="pb-6">
      <a href="/about" class="text-sm leading-6 text-gray-600 hover:text-gray-900">About</a>
    </div>
  </nav>
  <div class="mt-10 flex justify-center space-x-10">
    <a href="https://twitter.com/adnjoo" class="text-gray-400 hover:text-gray-500">
      <span class="sr-only">X</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path d="M13.6823 10.6218L20.2391 3H18.6854L12.9921 9.61788L8.44486 3H3.2002L10.0765 13.0074L3.2002 21H4.75404L10.7663 14.0113L15.5685 21H20.8131L13.6819 10.6218H13.6823ZM11.5541 13.0956L10.8574 12.0991L5.31391 4.16971H7.70053L12.1742 10.5689L12.8709 11.5655L18.6861 19.8835H16.2995L11.5541 13.096V13.0956Z" />
      </svg>
    </a>
    <a href="https://github.com/adnjoo/smalltrack-rails" class="text-gray-400 hover:text-gray-500">
      <span class="sr-only">GitHub</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
      </svg>
    </a>
  </div>
  <p class="mt-10 text-center text-xs leading-5 text-gray-500">&copy; 2024 SmallTrack, Inc. All rights reserved.</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" id="mobile-menu-button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <a class="flex flex-shrink-0 items-center" href="/">
          <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </a>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <a href="/" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Dashboard</a>
            <a href="/about" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">About</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="/" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" aria-current="page">Dashboard</a>
      <a href="/about" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">About</a>
    </div>
  </div>
</nav>
<!-- Toggle mobile menu button -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    const mobileMenuButton = document.getElementById('mobile-menu-button');
    const mobileMenu = document.getElementById('mobile-menu');

    mobileMenuButton.addEventListener('click', function() {
      const isExpanded = mobileMenu.getAttribute('aria-expanded') === 'true';
      mobileMenu.setAttribute('aria-expanded', !isExpanded);
      mobileMenu.classList.toggle('hidden');
    });
  });
</script>